#! /bin/sh

sh pgrep -x sxhkd > /dev/null || sxhkd &

if [ $(xrandr | grep -c "HDMI-1 connected") -eq 1 ]; then
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
    bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         1
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Vivaldi-snapshot desktop='^2' follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pcmanfm desktop='^5' follow=on
bspc rule -a Thunar desktop='^5' follow=on
bspc rule -a notion-app desktop='^6'
bspc rule -a Postman desktop='^7'
bspc rule -a beekeeper-studio desktop='^7'
bspc rule -a Spotify desktop='^8'
bspc rule -a Stremio desktop='^8' follow=on
bspc rule -a Slack desktop='^9'
bspc rule -a zoom desktop='^9'
bspc rule -a discord-screenaudio desktop='^9'
bspc rule -a xfce4-terminal state=floating

bspc rule -a WebApp-Excalidraw1017 desktop='^6' follow=on
bspc rule -a WebApp-Gmail3935 desktop='^7'
bspc rule -a thunderbird desktop='^7'
bspc rule -a WebApp-googlemeet4031 desktop='^9'
bspc rule -a WebApp-whatsapp6692 desktop='^10'
bspc rule -a WebApp-Starplus9374 desktop='^10' follow=on
bspc rule -a WebApp-Netflix2056 desktop='^10' follow=on
bspc rule -a chatGPTWebApp desktop='^10' follow=on
bspc rule -a TelegramDesktop desktop='^10' follow=on


bspc rule -a AlacrittyGame state=floating sticky=on rectangle=440x130+925+656

# Border
bspc config focused_border_color        "#800080"
bspc config normal_border_color         "#300130"
bspc config active_border_color         "#300130"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Disable screen blanking
xset -dpms
xset s off

# xfce4-power-manager
xfce4-power-manager &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
