[font]
# draw_bold_text_with_bright_colors = true
size = 8

[font.bold]
family = "JetBrainsMono NFP"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFP"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFP"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFP"
style = "Medium"
