#!/bin/bash

spotify_status=$(playerctl -p spotify status 2>/dev/null)
spotifyd_status=$(playerctl -p spotifyd status 2>/dev/null)

if [ "$spotify_status" == "Playing" ] || [ "$spotifyd_status" == "Playing" ]; then
  if [ "$spotify_status" == "Playing" ]; then
    title=$(playerctl -p spotify metadata xesam:title)
    artist=$(playerctl -p spotify metadata xesam:artist)
  else
    title=$(playerctl -p spotifyd metadata xesam:title)
    artist=$(playerctl -p spotifyd metadata xesam:artist)
  fi
  echo " %{T2} $title - $artist%{T-}"
elif [ "$spotify_status" == "Paused" ] || [ "$spotifyd_status" == "Paused" ]; then
  if [ "$spotify_status" == "Paused" ]; then
    title=$(playerctl -p spotify metadata xesam:title)
    artist=$(playerctl -p spotify metadata xesam:artist)
  else
    title=$(playerctl -p spotifyd metadata xesam:title)
    artist=$(playerctl -p spotifyd metadata xesam:artist)
  fi
  echo "  %{T2}$title - $artist%{T-}"
else
  echo ""
fi

##!/bin/bash

#if [ "$(playerctl -p spotify status >>/dev/null 2>&1; echo $?)" == "1" ]
#then
#	echo ""
#	exit 0
#fi

#if [ "$(playerctl -p spotify status)" == "Playing" ]
#then
#	echo "%{T1}%{T-}"
#elif [ "$(playerctl -p spotify status)" == "Paused" ]
#then
#	echo "%{T1}%{T1}"
#else
#	exit 0
#fi
